title: Yujia Chen's Homepage
page-top-title: Yujia Chen
top-section-bg-text: Medical artificial intelligence
home-subtitle: Yujia Chen&ensp;|&ensp;陈裕佳
copyright-text: '&copy; Yujia Chen 2023-2025. All Rights Reserved.'
