title: Yujia Chen's Homepage
page-top-title: Yujia Chen
top-section-bg-text: Medical artificial intelligence
home-subtitle: &ensp;|&ensp;陈裕佳
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
